[package]
name = "kube-auth"
version = "0.1.0"
authors = ["Nate Strandberg <nater540@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.19"
actix = "0.8.1"
serde_yaml = "0.8.8"
serde_json = "1.0.39"
serde = { version = "1.0.90", features = ["derive"] }
